services:
  rd-sync:
    image: ghcr.io/maulik9898/rd-sync:main
    container_name: rd-sync
    restart: unless-stopped
    volumes:
      # Mount your local config directory
      - ${CONFIG_PATH:-./config}:/config:ro # Use CONFIG_PATH env var or default to ./config
      - ${LOGS_PATH:-./logs}:/logs # Use LOGS_PATH env var or default to ./logs
    environment:
      - TZ=Asia/Kolkata
      - FORCE_COLOR=1
      - TERM=xterm-256color
